"""itital migration

Revision ID: 7b3bb1512e10
Revises: 
Create Date: 2022-03-05 13:51:46.922076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3bb1512e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('food',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=80), nullable=False),
    sa.Column('food_qty', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('food_id'),
    sa.UniqueConstraint('food_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
